AhaKnow/blueprints/admin.py
# -*- coding: utf-8 -*-
"""
    @Author: Zeal Young
    @URL: https://ahaknow.com
    @Create: 2021/9/9 21:07
"""
from flask import Blueprint, render_template, redirect, url_for, request, current_app, flash
from flask_login import login_required, current_user
from datetime import datetime

from AhaKnow.forms import SettingForm, PostForm, CategoryForm, LinkForm
from AhaKnow.utils import redirect_back, slugify
from AhaKnow.extensions import db
from AhaKnow.models import Post, Category, Comment, Link

admin_bp = Blueprint('admin', __name__)


@admin_bp.before_request
@login_required
def login_protect():
    pass


@admin_bp.route('/settings', methods=['GET', 'POST'])
def settings():
    form = SettingForm()
    if form.validate_on_submit():
        current_user.name = form.name.data
        current_user.blog_title = form.blog_title.data
        current_user.blog_sub_title = form.blog_sub_title.data
        current_user.body = form.body.data
        db.session.commit()
        flash('Setting updated.', 'success')
        return redirect(url_for('blog.index'))
    form.name.data = current_user.name
    form.blog_title.data = current_user.blog_title
    form.blog_sub_title = current_user.blog_sub_title
    form.body.data = current_user.body
    return render_template('admin/settings.html', form=form)


@admin_bp.route('/post/manage')
def manage_post():
    page = request.args.get('page', 1, type=int)
    pagination = Post.query.order_by(Post.timestamp.desc()).paginate(
        page, per_page=current_app.config['BLOG_MANAGE_POST_PER_PAGE'])
    posts = pagination.items
    return render_template('admin/manage_post.html', page=page, pagination=pagination, posts=posts)


@admin_bp.route('/post/new', methods=['GET', 'POST'])
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        title = form.title.data
        if form.slug.data:
            slug = form.slug.data
        else:
            slug = slugify(form.title.data)
        body = form.body.data
        category = Category.query.get(form.category.data)
        post = Post(title=title, body=body, slug=slug, category=category)
        db.session.add(post)
        db.session.commit()
        flash('Post published.', 'success')
        return redirect(url_for('blog.show_post', slug=post.slug))
    return render_template('admin/new_post.html', form=form)


@admin_bp.route('/post/<int:post_id>/edit', methods=['GET', 'POST'])
def edit_post(post_id):
    form = PostForm()
    post = Post.query.get_or_404(post_id)
    if form.validate_on_submit():
        post.title = form.title.data
        if form.slug.data:
            post.slug = form.slug.data
        else:
            post.slug = slugify(form.title.data)
        post.body = form.body.data
        post.category = Category.query.get(form.category.data)
        post.last_timestamp = datetime.utcnow()
        db.session.commit()
        flash('Post updated.', 'success')
        return redirect(url_for('blog.show_post', slug=post.slug))
    form.title.data = post.title
    form.slug.data = post.slug
    form.body.data = post.body
    form.category.data = post.category_name
    return render_template('admin/edit_post.html', form=form)


@admin_bp.route('/post/<int:post_id>/delete', methods=['POST'])
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    db.session.delete(post)
    db.session.commit()
    flash('Post already gone.', 'success')
    return redirect_back()


@admin_bp.route('/post/<int:post_id>/hide', methods=['POST'])
def hide_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.private:
        post.private = False
        flash('Post is shown.', 'success')
    else:
        post.private = True
        flash('Post is hidden.', 'success')
    db.session.commit()
    return redirect_back()


@admin_bp.route('/post/<int:post_id>/set-comment', methods=['POST'])
def set_comment(post_id):
    post = Post.query.get_or_404(post_id)
    if post.can_comment:
        post.can_comment = False
        flash('Comment disabled.', 'success')
    else:
        post.can_comment = True
        flash('Comment enabled.', 'success')
    db.session.commit()
    return redirect_back()


@admin_bp.route('/comment/manage')
def manage_comment():
    filter_rule = request.args.get('filter', 'all')  # 'all', 'unreviewed', 'admin'
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['BLOG_MANAGE_COMMENT_PER_PAGE']
    if filter_rule == 'unread':
        filtered_comments = Comment.query.filter_by(reviewed=False)
    elif filter_rule == 'admin':
        filtered_comments = Comment.query.filter_by(from_admin=True)
    else:
        filtered_comments = Comment.query
    pagination = filtered_comments.order_by(Comment.timestamp.desc()).paginate(page, per_page=per_page)
    comments = pagination.items
    return render_template('admin/manage_comment.html', comments=comments, pagination=pagination)


@admin_bp.route('/comment/<int:comment_id>/approve', methods=['POST'])
def approve_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    comment.reviewed = True
    db.session.commit()
    flash('Comment published.', 'success')
    return redirect_back()


@admin_bp.route('/comment/<int:comment_id>/delete', methods=['POST'])
def delete_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    db.session.delete(comment)
    db.session.commit()
    flash('Comment deleted.', 'success')
    return redirect_back()


@admin_bp.route('/category/manage')
def manage_category():
    return render_template('admin/manage_category.html')


@admin_bp.route('/category/new', methods=['GET', 'POST'])
def new_category():
    form = CategoryForm()
    if form.validate_on_submit():
        name = form.name.data
        category = Category(name=name)
        db.session.add(category)
        db.session.commit()
        flash('Category: {} created.'.format(name), 'success')
        return redirect(url_for('.manage_category'))
    return render_template('admin/new_category.html', form=form)


@admin_bp.route('/category/<category_name>/edit', methods=['GET', 'POST'])
def edit_category(category_name):
    form = CategoryForm()
    category = Category.query.filter_by(name=category_name).first_or_404()
    if category.id == 1:
        flash('Unnamed is well, Do not change it.', 'warning')
        return redirect(url_for('blog.index'))
    if form.validate_on_submit():
        category.name = form.name.data
        db.session.commit()
        flash('Category: {} updated.'.format(category_name), 'success')
        return redirect(url_for('.manage_category'))
    return render_template('admin/edit_category.html', form=form)


@admin_bp.route('/category/<category_name>/delete', methods=['POST'])
def delete_category(category_name):
    category = Category.query.filter_by(name=category_name).first_or_404()
    if category.id == 1:
        flash('You can not do this! Unless you want to drop the whole site.', 'danger')
        return redirect(url_for('blog.index'))
    category.delete()  # use Category.delete() in models.py
    flash('Category: {} deleted.'.format(category_name), 'success')
    return redirect(url_for('.manage_category'))


@admin_bp.route('/link/manage')
def manage_link():
    return render_template('admin/manage_link.html')


@admin_bp.route('/link/new', methods=['GET', 'POST'])
def new_link():
    form = LinkForm()
    if form.validate_on_submit():
        name = form.name.data
        url = form.url.data
        link = Link(name=name, url=url)
        db.session.add(link)
        db.session.commit()
        flash('Link: {} created.'.format(name), 'success')
        return redirect(url_for('.manage_link'))
    return render_template('admin/new_link.html', form=form)


@admin_bp.route('/link/<int:link_id>/edit', methods=['GET', 'POST'])
def edit_link(link_id):
    form = LinkForm()
    link = Link.query.get_or_404(link_id)
    if form.validate_on_submit():
        link.name = form.name.data
        link.url = form.url.data
        db.session.commit()
        flash('Link: {} updated.'.format(link.name), 'success')
        return redirect(url_for('.manage_link'))
    form.name.data = link.name
    form.url.data = link.url
    return render_template('admin/edit_link.html', form=form)


@admin_bp.route('/link/<int:link_id>/delete', methods=['POST'])
def delete_link(link_id):
    link = Link.query.get_or_404(link_id)
    db.session.delete(link)
    db.session.commit()
    flash('Link: {} deleted.'.format(link.name), 'success')
    return redirect(url_for('.manage_link'))

AhaKnow/blueprints/auth.py
# -*- coding: utf-8 -*-
"""
    @Author: Zeal Young
    @URL: https://ahaknow.com
    @Create: 2021/9/9 21:07
"""
from flask import Blueprint, render_template, redirect, url_for, flash
# Login and logout
from flask_login import login_user, login_required, logout_user, current_user

from AhaKnow.forms import LoginForm
from AhaKnow.utils import redirect_back
# Login and logout
from AhaKnow.models import Admin

auth_bp = Blueprint('auth', __name__)


@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('blog.index'))

    form = LoginForm()
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        remember = form.remember.data
        admin = Admin.query.first()
        if admin:
            if username == admin.username and admin.validate_password(password):
                login_user(admin, remember)
                flash('Welcome Back.', 'success')
                return redirect_back()
            flash('Is there one missing character in password?', 'warning')
        else:
            flash('Illegal invasion!', 'danger')
    return render_template('auth/login.html', form=form)


@auth_bp.route('/logout')
@login_required
def logout():
    logout_user()
    flash('Farewell.', 'info')
    return redirect_back()

AhaKnow/blueprints/blog.py
# -*- coding: utf-8 -*-
"""
    @Author: Zeal Young
    @URL: https://ahaknow.com
    @Create: 2021/9/9 21:07
"""
from flask import Blueprint, render_template, request, current_app, abort, make_response, flash, redirect, url_for
from flask_login import current_user

from AhaKnow.emails import send_new_comment_email, send_new_reply_email
from AhaKnow.models import Post, Category, Comment
from AhaKnow.utils import redirect_back
from AhaKnow.forms import AdminCommentForm, CommentForm
from AhaKnow.extensions import db

blog_bp = Blueprint('blog', __name__)


# # Flask-Login
# class current_user:
#     is_authenticated = False


@blog_bp.route('/')
def index():
    # posts = Post.query.order_by(Post.timestamp.desc()).all()
    # return render_template('blog/index.html', posts=posts)
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['BLOG_POST_PER_PAGE']
    if current_user.is_authenticated:
        pagination = Post.query.order_by(Post.timestamp.desc()).paginate(page, per_page=per_page)
    else:
        pagination = Post.query.filter_by(private=False).order_by(Post.timestamp.desc()).paginate(page,
                                                                                                  per_page=per_page)
    posts = pagination.items
    return render_template('blog/index.html', pagination=pagination, posts=posts)


@blog_bp.route('/about')
def about():
    return render_template('blog/about.html')


@blog_bp.route('/overview')
def overview():
    if current_user.is_authenticated:
        posts = Post.query.order_by(Post.timestamp.desc())
    else:
        posts = Post.query.filter_by(private=False).order_by(Post.timestamp.desc())
    return render_template('blog/overview.html', posts=posts)


@blog_bp.route('/category/<category_name>')
def show_category(category_name):
    category = Category.query.filter_by(name=category_name).first_or_404()
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['BLOG_POST_PER_PAGE']
    # Add query filter
    if current_user.is_authenticated:
        pagination = Post.query.with_parent(category).order_by(Post.timestamp.desc()).paginate(page, per_page=per_page)
    else:
        pagination = Post.query.with_parent(category).filter_by(private=False).order_by(Post.timestamp.desc()).paginate(
            page, per_page=per_page)
    posts = pagination.items
    return render_template('blog/category.html', category=category, pagination=pagination, posts=posts)


@blog_bp.route('/post/<slug>', methods=['GET', 'POST'])
def show_post(slug):
    post = Post.query.filter_by(slug=slug).first_or_404()
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['BLOG_COMMENT_PER_PAGE']
    # desc() = descending, asc() = ascending
    pagination = Comment.query.with_parent(post).filter_by(reviewed=True).order_by(Comment.timestamp.asc()).paginate(
        page, per_page)
    comments = pagination.items

    if current_user.is_authenticated:
        form = AdminCommentForm()
        form.author.data = current_user.name  # need Flask-Login
        form.email.data = current_app.config['BLOG_EMAIL']
        form.site.data = url_for('.index')
        from_admin = True
        reviewed = True
    else:
        form = CommentForm()
        from_admin = False
        reviewed = False

    if form.validate_on_submit():
        author = form.author.data
        email = form.email.data
        site = form.site.data
        body = form.body.data
        comment = Comment(
            author=author, email=email, site=site, body=body,
            post=post, from_admin=from_admin, reviewed=reviewed)
        replied_id = request.args.get('reply')
        if replied_id:
            replied_comment = Comment.query.get_or_404(replied_id)
            comment.replied = replied_comment
            send_new_reply_email(replied_comment)
        db.session.add(comment)
        db.session.commit()
        if current_user.is_authenticated:
            flash('Comment published.', 'success')
        else:
            flash('Thanks, your comment will be published after reviewed.', 'info')
            send_new_comment_email(post)  # to admin
        return redirect(url_for('.show_post', slug=slug))
    if request.method == 'POST' and not form.validate():
        flash('Maybe some information wrong, please check and try again.', 'warning')
    return render_template('blog/post.html', post=post, pagination=pagination, form=form, comments=comments)


@blog_bp.route('/reply/comment/<int:comment_id>')
def reply_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    if not comment.post.can_comment:
        flash('Only Read, No Discuss.', 'warning')
        return redirect(url_for('.show_post', slug=comment.post.slug))
    return redirect(
        url_for('.show_post', slug=comment.post.slug, reply=comment_id, author=comment.author) + '#commentForm')


@blog_bp.route('/change-theme/<theme_name>')
def change_theme(theme_name):
    if theme_name not in current_app.config['BLOG_THEMES'].keys():
        abort(404)

    response = make_response(redirect_back())
    response.set_cookie('theme', theme_name, max_age=60 * 60 * 24 * 30)
    return response

AhaKnow/templates/base.html
{# use bootstrap-flask #}
{% from 'bootstrap/nav.html' import render_nav_item %}
{% from 'blog/_macros.html' import nav_link %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}{% endblock title %} | {{ admin.blog_title|default('AhaKnow') }}</title>
        <link rel="icon" href="{{ url_for('static', filename='favicon/favicon.ico') }}">
        <link rel="stylesheet"
              href="{{ url_for('static', filename='css/%s.bootstrap.min.css' % request.cookies.get('theme', 'sketchy')) }}"
              type="text/css">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" type="text/css">
    {% endblock head %}
</head>
<body>
<header>
    {% block nav %}
        <nav class="fixed-top navbar navbar-expand-md {% if request.cookies.get('theme', 'sketchy')=='sketchy' %}navbar-light bg-light{% else %}navbar-dark bg-primary{% endif %}">
            <div class="container-md">
                <a class="navbar-brand" href="{{ url_for('blog.index') }}">{{ admin.blog_title|default('AhaKnow') }}</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor03"
                        aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarColor03">
                    <ul class="navbar-nav mt-2 mr-auto">
                        {{ render_nav_item('blog.overview', 'Overview') }}
                        {{ render_nav_item('blog.about', 'About') }}
                        {% if categories %}
                            <li class="nav-item dropdown show">
                                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button"
                                   aria-haspopup="true" aria-expanded="false">Category</a>
                                <div class="dropdown-menu">
                                    {% for category in categories %}
                                        <a class="dropdown-item d-flex justify-content-between"
                                           href="{{ url_for('blog.show_category', category_name=category.name) }}">
                                            {{ category.name }}
                                            <span class="badge badge-pill badge-light">{{ category.posts|length }}</span>
                                        </a>
                                    {% endfor %}
                                </div>
                            </li>
                        {% endif %}

                        {% if links %}
                            <li class="nav-item dropdown show">
                                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button"
                                   aria-haspopup="true" aria-expanded="false">Link</a>
                                <div class="dropdown-menu">
                                    {% for link in links %}
                                        <a class="dropdown-item" href="{{ link.url }}" target="_blank">
                                            {{ link.name }}</a>
                                    {% endfor %}
                                </div>
                            </li>
                        {% endif %}

                        <li class="nav-item dropdown show">
                            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button"
                               aria-haspopup="true" aria-expanded="false">Theme</a>
                            <div class="dropdown-menu">
                                {% for theme_name, display_name in config.BLOG_THEMES.items() %}
                                    {% if display_name=='minty' %}
                                        <div class="dropdown-divider"></div>
                                    {% endif %}
                                    <a class="dropdown-item"
                                       href="{{ url_for('blog.change_theme', theme_name=theme_name, next=request.full_path) }}">{{ display_name }}</a>
                                {% endfor %}
                            </div>
                        </li>
                    </ul>
                    <ul class="navbar-nav mt-2 ml-auto">
                        {% if current_user.is_authenticated %}
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button"
                                   aria-haspopup="true" aria-expanded="false">New</a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" href="{{ url_for('admin.new_post') }}">Post</a>
                                    <a class="dropdown-item" href="{{ url_for('admin.new_category') }}">Category</a>
                                    <a class="dropdown-item" href="{{ url_for('admin.new_link') }}">Link</a>
                                </div>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button"
                                   aria-haspopup="true" aria-expanded="false">
                                    Manage
                                    {% if unread_comments %}
                                        <span class="badge badge-pill badge-info">new</span>
                                    {% endif %}
                                </a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" href="{{ url_for('admin.manage_post') }}">Post</a>
                                    <a class="dropdown-item" href="{{ url_for('admin.manage_category') }}">Category</a>
                                    <a class="dropdown-item" href="{{ url_for('admin.manage_link') }}">Link</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item d-flex" href="{{ url_for('admin.manage_comment') }}">
                                        Comment
                                        {% if unread_comments %}
                                            <span class="ml-auto badge badge-pill badge-light">{{ unread_comments }}</span>
                                        {% endif %}
                                    </a>
                                </div>
                            </li>
                            {{ nav_link('admin.settings', 'Settings') }}
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
    {% endblock nav %}
</header>

<main class="container-md">
    {% for message in get_flashed_messages(with_categories=True) %}
        <div class="alert alert-dismissible alert-{{ message[0] }}">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ message[1] }}
        </div>
    {% endfor %}

    {% block content %}
    {% endblock content %}

    {% block footer %}
        <div class="margin-bottom text-muted d-flex justify-content-between">
            <div>
                &copy; 2021 - {{ date_now.year }} <a href="https://github.com/IHKYoung/AhaKnow" target="_blank"
                                              title="Design by Zeal Young">&hearts; Zeal Young</a>
            </div>
            <div>
                {% if current_user.is_authenticated %}
                    <a class="mr-1" href="{{ url_for('auth.logout', next=request.full_path) }}">Logout</a>
                {% endif %}
                <a href="#">Back to Top</a>
            </div>
        </div>
    {% endblock footer %}
</main>

{% block scripts %}
    <script type="application/javascript" src="{{ url_for('static', filename='js/jquery-3.5.1.min.js') }}"></script>
    {#    <script type="application/javascript" src="{{ url_for('static', filename='js/popper.min.js') }}"></script>#}
    <script type="application/javascript" src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>
    <script type="application/javascript" src="{{ url_for('static', filename='js/clipboard.min.js') }}"></script>
    <script type="application/javascript" src="{{ url_for('static', filename='js/script.js') }}"></script>
    {{ moment.include_moment(local_js=url_for('static', filename='js/moment-with-locales.min.js')) }}
{% endblock scripts %}

</body>
</html>