AhaKnow/blueprints/admin.py
# -*- coding: utf-8 -*-
"""
    @Author: Zeal Young
    @URL: https://ahaknow.com
    @Create: 2021/9/9 21:07
"""
from flask import Blueprint, render_template, redirect, url_for, request, current_app, flash
from flask_login import login_required, current_user
from datetime import datetime

from AhaKnow.forms import SettingForm, PostForm, CategoryForm, LinkForm
from AhaKnow.utils import redirect_back, slugify
from AhaKnow.extensions import db
from AhaKnow.models import Post, Category, Comment, Link

admin_bp = Blueprint('admin', __name__)


@admin_bp.before_request
@login_required
def login_protect():
    pass


@admin_bp.route('/settings', methods=['GET', 'POST'])
def settings():
    form = SettingForm()
    if form.validate_on_submit():
        current_user.name = form.name.data
        current_user.blog_title = form.blog_title.data
        current_user.blog_sub_title = form.blog_sub_title.data
        current_user.body = form.body.data
        db.session.commit()
        flash('Setting updated.', 'success')
        return redirect(url_for('blog.index'))
    form.name.data = current_user.name
    form.blog_title.data = current_user.blog_title
    form.blog_sub_title = current_user.blog_sub_title
    form.body.data = current_user.body
    return render_template('admin/settings.html', form=form)


@admin_bp.route('/post/manage')
def manage_post():
    page = request.args.get('page', 1, type=int)
    pagination = Post.query.order_by(Post.timestamp.desc()).paginate(
        page, per_page=current_app.config['BLOG_MANAGE_POST_PER_PAGE'])
    posts = pagination.items
    return render_template('admin/manage_post.html', page=page, pagination=pagination, posts=posts)


@admin_bp.route('/post/new', methods=['GET', 'POST'])
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        title = form.title.data
        if form.slug.data:
            slug = form.slug.data
        else:
            slug = slugify(form.title.data)
        body = form.body.data
        category = Category.query.get(form.category.data)
        post = Post(title=title, body=body, slug=slug, category=category)
        db.session.add(post)
        db.session.commit()
        flash('Post published.', 'success')
        return redirect(url_for('blog.show_post', slug=post.slug))
    return render_template('admin/new_post.html', form=form)


@admin_bp.route('/post/<int:post_id>/edit', methods=['GET', 'POST'])
def edit_post(post_id):
    form = PostForm()
    post = Post.query.get_or_404(post_id)
    if form.validate_on_submit():
        post.title = form.title.data
        if form.slug.data:
            post.slug = form.slug.data
        else:
            post.slug = slugify(form.title.data)
        post.body = form.body.data
        post.category = Category.query.get(form.category.data)
        post.last_timestamp = datetime.utcnow()
        db.session.commit()
        flash('Post updated.', 'success')
        return redirect(url_for('blog.show_post', slug=post.slug))
    form.title.data = post.title
    form.slug.data = post.slug
    form.body.data = post.body
    form.category.data = post.category_name
    return render_template('admin/edit_post.html', form=form)


@admin_bp.route('/post/<int:post_id>/delete', methods=['POST'])
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    db.session.delete(post)
    db.session.commit()
    flash('Post already gone.', 'success')
    return redirect_back()


@admin_bp.route('/post/<int:post_id>/hide', methods=['POST'])
def hide_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.private:
        post.private = False
        flash('Post is shown.', 'success')
    else:
        post.private = True
        flash('Post is hidden.', 'success')
    db.session.commit()
    return redirect_back()


@admin_bp.route('/post/<int:post_id>/set-comment', methods=['POST'])
def set_comment(post_id):
    post = Post.query.get_or_404(post_id)
    if post.can_comment:
        post.can_comment = False
        flash('Comment disabled.', 'success')
    else:
        post.can_comment = True
        flash('Comment enabled.', 'success')
    db.session.commit()
    return redirect_back()


@admin_bp.route('/comment/manage')
def manage_comment():
    filter_rule = request.args.get('filter', 'all')  # 'all', 'unreviewed', 'admin'
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['BLOG_MANAGE_COMMENT_PER_PAGE']
    if filter_rule == 'unread':
        filtered_comments = Comment.query.filter_by(reviewed=False)
    elif filter_rule == 'admin':
        filtered_comments = Comment.query.filter_by(from_admin=True)
    else:
        filtered_comments = Comment.query
    pagination = filtered_comments.order_by(Comment.timestamp.desc()).paginate(page, per_page=per_page)
    comments = pagination.items
    return render_template('admin/manage_comment.html', comments=comments, pagination=pagination)


@admin_bp.route('/comment/<int:comment_id>/approve', methods=['POST'])
def approve_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    comment.reviewed = True
    db.session.commit()
    flash('Comment published.', 'success')
    return redirect_back()


@admin_bp.route('/comment/<int:comment_id>/delete', methods=['POST'])
def delete_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    db.session.delete(comment)
    db.session.commit()
    flash('Comment deleted.', 'success')
    return redirect_back()


@admin_bp.route('/category/manage')
def manage_category():
    return render_template('admin/manage_category.html')


@admin_bp.route('/category/new', methods=['GET', 'POST'])
def new_category():
    form = CategoryForm()
    if form.validate_on_submit():
        name = form.name.data
        category = Category(name=name)
        db.session.add(category)
        db.session.commit()
        flash('Category: {} created.'.format(name), 'success')
        return redirect(url_for('.manage_category'))
    return render_template('admin/new_category.html', form=form)


@admin_bp.route('/category/<category_name>/edit', methods=['GET', 'POST'])
def edit_category(category_name):
    form = CategoryForm()
    category = Category.query.filter_by(name=category_name).first_or_404()
    if category.id == 1:
        flash('Unnamed is well, Do not change it.', 'warning')
        return redirect(url_for('blog.index'))
    if form.validate_on_submit():
        category.name = form.name.data
        db.session.commit()
        flash('Category: {} updated.'.format(category_name), 'success')
        return redirect(url_for('.manage_category'))
    return render_template('admin/edit_category.html', form=form)


@admin_bp.route('/category/<category_name>/delete', methods=['POST'])
def delete_category(category_name):
    category = Category.query.filter_by(name=category_name).first_or_404()
    if category.id == 1:
        flash('You can not do this! Unless you want to drop the whole site.', 'danger')
        return redirect(url_for('blog.index'))
    category.delete()  # use Category.delete() in models.py
    flash('Category: {} deleted.'.format(category_name), 'success')
    return redirect(url_for('.manage_category'))


@admin_bp.route('/link/manage')
def manage_link():
    return render_template('admin/manage_link.html')


@admin_bp.route('/link/new', methods=['GET', 'POST'])
def new_link():
    form = LinkForm()
    if form.validate_on_submit():
        name = form.name.data
        url = form.url.data
        link = Link(name=name, url=url)
        db.session.add(link)
        db.session.commit()
        flash('Link: {} created.'.format(name), 'success')
        return redirect(url_for('.manage_link'))
    return render_template('admin/new_link.html', form=form)


@admin_bp.route('/link/<int:link_id>/edit', methods=['GET', 'POST'])
def edit_link(link_id):
    form = LinkForm()
    link = Link.query.get_or_404(link_id)
    if form.validate_on_submit():
        link.name = form.name.data
        link.url = form.url.data
        db.session.commit()
        flash('Link: {} updated.'.format(link.name), 'success')
        return redirect(url_for('.manage_link'))
    form.name.data = link.name
    form.url.data = link.url
    return render_template('admin/edit_link.html', form=form)


@admin_bp.route('/link/<int:link_id>/delete', methods=['POST'])
def delete_link(link_id):
    link = Link.query.get_or_404(link_id)
    db.session.delete(link)
    db.session.commit()
    flash('Link: {} deleted.'.format(link.name), 'success')
    return redirect(url_for('.manage_link'))

AhaKnow/blueprints/blog.py
# -*- coding: utf-8 -*-
"""
    @Author: Zeal Young
    @URL: https://ahaknow.com
    @Create: 2021/9/9 21:07
"""
from flask import Blueprint, render_template, request, current_app, abort, make_response, flash, redirect, url_for
from flask_login import current_user

from AhaKnow.emails import send_new_comment_email, send_new_reply_email
from AhaKnow.models import Post, Category, Comment
from AhaKnow.utils import redirect_back
from AhaKnow.forms import AdminCommentForm, CommentForm
from AhaKnow.extensions import db

blog_bp = Blueprint('blog', __name__)


# # Flask-Login
# class current_user:
#     is_authenticated = False


@blog_bp.route('/')
def index():
    # posts = Post.query.order_by(Post.timestamp.desc()).all()
    # return render_template('blog/index.html', posts=posts)
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['BLOG_POST_PER_PAGE']
    if current_user.is_authenticated:
        pagination = Post.query.order_by(Post.timestamp.desc()).paginate(page, per_page=per_page)
    else:
        pagination = Post.query.filter_by(private=False).order_by(Post.timestamp.desc()).paginate(page,
                                                                                                  per_page=per_page)
    posts = pagination.items
    return render_template('blog/index.html', pagination=pagination, posts=posts)


@blog_bp.route('/about')
def about():
    return render_template('blog/about.html')


@blog_bp.route('/overview')
def overview():
    if current_user.is_authenticated:
        posts = Post.query.order_by(Post.timestamp.desc())
    else:
        posts = Post.query.filter_by(private=False).order_by(Post.timestamp.desc())
    return render_template('blog/overview.html', posts=posts)


@blog_bp.route('/category/<category_name>')
def show_category(category_name):
    category = Category.query.filter_by(name=category_name).first_or_404()
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['BLOG_POST_PER_PAGE']
    # Add query filter
    if current_user.is_authenticated:
        pagination = Post.query.with_parent(category).order_by(Post.timestamp.desc()).paginate(page, per_page=per_page)
    else:
        pagination = Post.query.with_parent(category).filter_by(private=False).order_by(Post.timestamp.desc()).paginate(
            page, per_page=per_page)
    posts = pagination.items
    return render_template('blog/category.html', category=category, pagination=pagination, posts=posts)


@blog_bp.route('/post/<slug>', methods=['GET', 'POST'])
def show_post(slug):
    post = Post.query.filter_by(slug=slug).first_or_404()
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['BLOG_COMMENT_PER_PAGE']
    # desc() = descending, asc() = ascending
    pagination = Comment.query.with_parent(post).filter_by(reviewed=True).order_by(Comment.timestamp.asc()).paginate(
        page, per_page)
    comments = pagination.items

    if current_user.is_authenticated:
        form = AdminCommentForm()
        form.author.data = current_user.name  # need Flask-Login
        form.email.data = current_app.config['BLOG_EMAIL']
        form.site.data = url_for('.index')
        from_admin = True
        reviewed = True
    else:
        form = CommentForm()
        from_admin = False
        reviewed = False

    if form.validate_on_submit():
        author = form.author.data
        email = form.email.data
        site = form.site.data
        body = form.body.data
        comment = Comment(
            author=author, email=email, site=site, body=body,
            post=post, from_admin=from_admin, reviewed=reviewed)
        replied_id = request.args.get('reply')
        if replied_id:
            replied_comment = Comment.query.get_or_404(replied_id)
            comment.replied = replied_comment
            send_new_reply_email(replied_comment)
        db.session.add(comment)
        db.session.commit()
        if current_user.is_authenticated:
            flash('Comment published.', 'success')
        else:
            flash('Thanks, your comment will be published after reviewed.', 'info')
            send_new_comment_email(post)  # to admin
        return redirect(url_for('.show_post', slug=slug))
    if request.method == 'POST' and not form.validate():
        flash('Maybe some information wrong, please check and try again.', 'warning')
    return render_template('blog/post.html', post=post, pagination=pagination, form=form, comments=comments)


@blog_bp.route('/reply/comment/<int:comment_id>')
def reply_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    if not comment.post.can_comment:
        flash('Only Read, No Discuss.', 'warning')
        return redirect(url_for('.show_post', slug=comment.post.slug))
    return redirect(
        url_for('.show_post', slug=comment.post.slug, reply=comment_id, author=comment.author) + '#commentForm')


@blog_bp.route('/change-theme/<theme_name>')
def change_theme(theme_name):
    if theme_name not in current_app.config['BLOG_THEMES'].keys():
        abort(404)

    response = make_response(redirect_back())
    response.set_cookie('theme', theme_name, max_age=60 * 60 * 24 * 30)
    return response

AhaKnow/templates/blog/_category.html
{% if posts %}
    {% for post in posts %}
        <div class="container-md my-4">
            <span class="text-muted my-auto">{{ moment(post.timestamp).format('ll') }}</span>
            <h3 class="fs-1 text-primary my-auto">
                <a href="{{ url_for('.show_post', slug=post.slug) }}">{{ post.title }}</a>
            </h3>
        </div>
    {% endfor %}
{% else %}
    <div class="mt-5 alert alert-dismissible alert-info">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <h4 class="alert-heading">Hey!</h4>
        <p class="mb-0">Heads up! Nothing here, you need to write some.
            <a href="{{ url_for('admin.new_post') }}" class="alert-link">Click here to write down your first
                article.</a>.</p>
    </div>
{% endif %}

AhaKnow/templates/blog/_macros.html
{# For Page Nagivation #}
{% macro pagenav(pagination, fragment='') %}
    <nav aria-label="Page navigation">
        <ul class="pagination">
            <li class="page-item {% if not pagination.has_prev %}disabled{% endif %}">
                <a href="{{ url_for(request.endpoint, page=pagination.prev_num, **kwargs) + fragment if pagination.has_prev else '#' }}"
                   class="page-link">
                    <span aria-hidden="true">&laquo;</span> Prev
                </a>
            </li>
            <li class="page-item {% if not pagination.has_next %}disabled{% endif %}">
                <a href="{{ url_for(request.endpoint, page=pagination.next_num, **kwargs) + fragment if pagination.has_next else '#' }}"
                   class="page-link">
                    <span aria-hidden="true">&raquo;</span> Next
                </a>
            </li>
        </ul>
    </nav>
{% endmacro %}

{% macro nav_link(endpoint, text) -%}
    <li class="nav-item" {% if request.endpoint
    and request.endpoint==endpoint %}active{% endif %}>
        <a href="{{ url_for(endpoint, **kwargs) }}" class="nav-link">{{ text }}</a>
    </li>
{%- endmacro %}

AhaKnow/templates/blog/_overview.html
{% if posts %}
    {% for post in posts %}
        <div class="container-md my-4">
            <span class="text-muted my-auto">{{ moment(post.timestamp).format('L') }}</span>
            <h3 class="fs-1 text-primary my-auto">
                <a href="{{ url_for('.show_post', slug=post.slug) }}">{{ post.title }}</a>
            </h3>
        </div>
    {% endfor %}
{% else %}
    <div class="mt-5 text-center">
        <h1 class="display-3">Waiting...</h1>
        <p class="lead">Waiting for? or waiting for see you.</p>
        <p class="lead">
            <a class="btn btn-primary btn-lg" href="{{ url_for('blog.index') }}" role="button">Take Me Home</a>
        </p>
    </div>
{% endif %}

AhaKnow/templates/blog/_posts.html
{% if posts %}
    {% for post in posts %}
        <div class="d-flex flex-column container-md my-4">
            <div class="d-flex mb-3 border-bottom">
                <h2 class="fs-2 text-primary my-auto">
                    <a href="{{ url_for('.show_post', slug=post.slug) }}">{{ post.title }}</a>
                </h2>
                <span class="text-muted my-auto ml-auto">
                {{ moment(post.timestamp).format('LL') }}</span>
            </div>
            <article class="article-preview">
                {% if post.body_html %}
                    {{ post.body_html|truncate(255, '...')|safe}}
                {% else %}
                    {{ post.body|truncate(255, '...')|safe}}
                {% endif %}
            </article>
            <div class="d-flex">
                <a id="readMore" class="btn btn-outline-primary btn-sm mr-auto"
                   href="{{ url_for('.show_post', slug=post.slug) }}"
                   role="button">Read more</a>
                <a href="{{ url_for('.show_post', slug=post.slug) + '#postComment' }} "
                   class="badge badge-success my-auto ml-1">
                    Comments: {{ post.comments|length }}</a>
                <a href="{{ url_for('.show_category', category_name=post.category.name) }}"
                   class="badge badge-info my-auto ml-1">
                    {{ post.category.name }}</a>
            </div>
        </div>
{#                {% if not loop.last %}#}
{#                    <hr>#}
{#                {% endif %}#}
    {% endfor %}
{% else %}
    <div class="mt-5 alert alert-dismissible alert-info">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <h4 class="alert-heading">Hey!</h4>
        <p class="mb-0">Heads up! Nothing here, you need to write some.
            <a href="{{ url_for('admin.new_post') }}" class="alert-link">Click here to write down your first
                article.</a>.</p>
    </div>
{% endif %}

AhaKnow/templates/blog/_sidebar.html
{% if categories %}
    <div class="card border-primary mb-3" style="max-width: 20rem;">
        <div class="card-header">Categories</div>
        <ul class="list-group">
            {% for category in categories %}
            <li class="list-group-item d-flex justify-content-between align-items-center">
                {#    to blog.show_category view function    #}
                <a href="{{ url_for('blog.show_category', category_name=category.name) }}">
                    {{ category.name }}
                </a>
                <span class="badge badge-primary badge-pill">{{ category.posts|length }}</span>
            </li>
            {% endfor %}
        </ul>
    </div>
{% endif %}

{% if links %}
    <div class="card border-secondary mb-3" style="max-width: 20rem;">
        <div class="card-header">Links</div>
        <ul class="list-group">
            {% for link in links %}
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <a href="{{ link.url }}" target="_blank">{{ link.name }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endif %}

AhaKnow/templates/blog/about.html
{% extends 'base.html' %}

{% block title %}About{% endblock %}

{% block content %}
    <div id="aboutBox">
        <h1 class="display-4">About Me.</h1>
        <p class="lead">
            {% if admin.body_html %}
                {{ admin.body_html|safe }}
            {% else %}
                {{ admin.body|safe }}
            {% endif %}
        </p>
        <hr class="my-4">
        <p class="lead">
            <a class="btn btn-primary btn" href="https://github.com/QuiteZeal" role="button">Know more</a>
        </p>
    </div>
{% endblock %}

AhaKnow/templates/blog/category.html
{% extends 'base.html' %}

{% block title %}{{ category.name }}{% endblock %}

{% block content %}
    <div>
        <h1 class="display-5">{{ category.name }}</h1>
    </div>
    <div class="row">
        <div class="col-sm-12">
            {% include 'blog/_category.html' %}
        </div>
    </div>
{% endblock %}

AhaKnow/templates/blog/index.html
{% extends 'base.html' %}
{#{% from 'blog/_macros.html' import pagenav %}#}
{% from 'bootstrap/pagination.html' import render_pagination %}

{% block title %}Home{% endblock %}

{% block content %}
    <div>
        <h1 class="display-3 mt-2 mb-1">{{ admin.blog_title|default('Blog Name') }}</h1>
        <h4 class="text-muted my-auto">{{ admin.blog_sub_title|default('Blog Descrpition') }}</h4>
    </div>
    <div>
        {% include 'blog/_posts.html' %}
        {% if posts %}
            {{ render_pagination(pagination) }}
            {#                {{ pagenav(pagination) }}#}
        {% endif %}
    </div>
{% endblock %}

AhaKnow/templates/blog/overview.html
{% extends 'base.html' %}

{% block title %}Overview{% endblock %}

{% block content %}
    <div>
        <h1 class="display-5">Overview</h1>
    </div>
    <div class="row">
        <div class="col-sm-12">
            {% include 'blog/_overview.html' %}
        </div>
    </div>
{% endblock %}

{% block footer %}{% endblock %}

AhaKnow/templates/blog/post.html
{% extends 'base.html' %}
{% from 'bootstrap/form.html' import render_form %}
{% from 'bootstrap/pagination.html' import render_pagination %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
    <div>
        <h1 class="display-5 my-2 pt-2">{{ post.title }}</h1>
        <div class="d-flex">
            <a href="{{ url_for('.show_category', category_name=post.category.name) }}"
               class="badge badge-info my-auto mr-1">
                {{ post.category.name }}</a>
            <a href="#postComment" class="badge badge-success my-auto mr-1">
                Comments: {{ post.comments|length }}</a>
            <a href="javascript:" class="badge badge-dark my-auto mr-auto">
                {#  use timestamp or last_timestamp   #}
                {{ moment(post.timestamp).format('lll') }}</a>
            {% if current_user.is_authenticated %}
                <a href="{{ url_for('admin.edit_post', post_id=post.id) }}" class="badge badge-info">Edit</a>
            {% else %}
                <a href="#" class="d-none d-sm-block badge badge-warning my-auto" data-toggle="modal"
                   data-target="#permalinkModal">
                    Share</a>
            {% endif %}
            <div id="permalinkModal" class="modal">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title">Permalink</h5>
                            <button type="button" class="close close-clear" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <div class="form-group">
                                <fieldset>
                                    <label class="control-label" for="readOnlyInput">Share Link</label>
                                    <input class="form-control" id="shareLink" type="text" readonly=""
                                           value="{{ url_for('.show_post', slug=post.slug, _external=True) }}">
                                </fieldset>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <p class='text-success hidden-first'>Copied</p>
                            <button type="button" class="btn btn-primary" data-clipboard-action="copy"
                                    data-clipboard-target="#shareLink">Copy
                            </button>
                            <button type="button" class="btn btn-secondary close-clear" data-dismiss="modal">Close
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <article class="article">
            {% if post.body_html %}
                {{ post.body_html|safe }}
            {% else %}
                {{ post.body|safe }}
            {% endif %}
        </article>
        <div id="postComment">
            <h3 class="d-flex">{{ comments|length }} Comments
                <small>
                    <a href="{{ url_for('.show_post', slug=post.slug, page=pagination.pages or 1) }}#postComment"
                       class="badge badge-light my-auto">Latest</a>
                </small>
                {% if current_user.is_authenticated %}
                    <form method="post" class="my-auto ml-auto"
                          action="{{ url_for('admin.set_comment', post_id=post.id, next=request.full_path) }}">
                        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                        <button type="submit" class="btn btn-sm btn-warning">
                            {% if post.can_comment %}Disable{% else %}Enable{% endif %}
                        </button>
                    </form>
                {% endif %}
            </h3>
            {% if comments %}
                <ul class="list-group">
                    {% for comment in comments %}
                        <div class="list-group-item list-group-item-action flex-column align-items-start">
                            <div class="d-flex w-100 justify-content-between">
                                <h5 class="mb-1">
                                    <a href="{% if comment.site %}{{ comment.site }}{% else %}#{% endif %}"
                                       target="_blank">
                                        {% if comment.from_admin %}
                                            {{ admin.name }}
                                        {% else %}
                                            {{ comment.author }}
                                        {% endif %}
                                    </a>
                                    {% if comment.from_admin %}
                                        <span class="badge badge-pill badge-primary">Author</span>
                                    {% endif %}
                                    {% if comment.replied %}
                                        <span class="badge badge-pill badge-secondary">Reply</span>
                                    {% endif %}
                                </h5>
                                <small data-toggle="tooltip" data-placement="top" data-delay="500"
                                       data-timestamp="{{ comment.timestamp.strftime('%Y-%m-%dT%H:%M:%SZ') }}">
                                    {{ moment(comment.timestamp).fromNow() }}
                                </small>
                            </div>
                            <p class="mb-1">{{ comment.body }}</p>
                            {% if comment.replied %}
                                <p class="alert alert-secondary">
                                    {{ comment.replied.author }} :
                                    <br>{{ comment.replied.body }}
                                </p>
                            {% endif %}
                            <div class="d-flex">
                                <a class="ml-auto mr-1 btn btn-outline-primary btn-sm"
                                   href="{{ url_for('.reply_comment', comment_id=comment.id) }}">Reply</a>
                                {% if current_user.is_authenticated %}
                                    <a href="mailto:{{ comment.email }}"
                                       class="mr-1 btn btn-outline-info btn-sm">Email</a>
                                    <form method="post"
                                          action="{{ url_for('admin.delete_comment', comment_id=comment.id, next=request.full_path) }}">
                                        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                                        <button type="submit" class="btn btn-outline-danger btn-sm"
                                                onclick="return confirm('Are you serious?');">Delete
                                        </button>
                                    </form>
                                {% endif %}
                            </div>
                        </div>
                    {% endfor %}
                </ul>
            {% else %}
                <div class="jumbotron text-center">
                    <h5 class="text-muted my-auto">Focus on Reading.</h5>
                </div>
            {% endif %}
        </div>
        {% if comments %}
            <div class="mt-3">
                {{ render_pagination(pagination, fragment='#postComment') }}
            </div>
        {% endif %}
        {% if request.args.get('reply') %}
            <div class="alert alert-secondary">
                Reply to <strong>{{ request.args.get('author') }}</strong> :
                <a class="float-right" href="{{ url_for('.show_post', slug=post.slug) }}">Cancel</a>
            </div>
        {% endif %}
        {% if post.can_comment %}
            <div id="commentForm">
                {{ render_form(form, action=request.full_path) }}
            </div>
        {% else %}
            <div id="commentForm">
                <div class="jumbotron text-center">
                    <h5 class="text-muted my-auto">Only Read. No Discuss.</h5>
                </div>
            </div>
        {% endif %}

    </div>
{% endblock %}